<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TS24.DataPlatform.Foundation/TS24.DataPlatform.Foundation.csproj" />
    <ProjectReference Include="../../src/TS24.DataPlatform.Provider.MariaDb/TS24.DataPlatform.Provider.MariaDb.csproj" />
  </ItemGroup>
</Project>
